version: '3.3'
   
services:
   backend_test:
    build: backend
    command: sh ./run.sh
    volumes:
      - ./backend:/srv/project
    ports:
      - "8081:8081"
   frontend_test:
    build: frontend
    container_name: frontend_test
    restart: always
    command: sh ./run.sh
    depends_on:
     - backend_test
    ports:
     - "3000:3000"
        
